language: node_js
node_js:
  - "node"
branches:
  only:
    - master
cache:
  yarn: true
script:
  - yarn run lint
  - yarn run test
  - yarn run build:prod
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
